import {
  Home,
  Building2,
  BedDouble,
  Sofa,
  Lightbulb,
  Plug,
  Droplet,
  Flame,
  Wifi,
  Trash2,
  Wrench,
  Hammer,
  ShoppingCart,
  ShoppingBag,
  Store,
  Package,
  Utensils,
  Coffee,
  Beer,
  Wine,
  Pizza,
  Apple,
  Carrot,
  Milk,
  Cookie,
  Beef,
  Fish,
  IceCream,
  Car,
  Truck,
  Bus,
  TramFront,
  Bike,
  Fuel,
  Plane,
  Ship,
  MapPin,
  Heart,
  HeartPulse,
  Stethoscope,
  Pill,
  Cross,
  Activity,
  Dumbbell,
  Bath,
  Scissors,
  Sparkles,
  Baby,
  Dog,
  Cat,
  PawPrint,
  GraduationCap,
  BookOpen,
  Book,
  Pencil,
  Briefcase,
  Wallet,
  PiggyBank,
  Banknote,
  Coins,
  CreditCard,
  DollarSign,
  TrendingUp,
  Landmark,
  HandCoins,
  Receipt,
  FileText,
  Gift,
  PartyPopper,
  Gamepad2,
  Music,
  Film,
  Tv,
  Ticket,
  Camera,
  Headphones,
  Shirt,
  Footprints,
  Phone,
  Smartphone,
  Laptop,
  Monitor,
  Umbrella,
  Sun,
  TreePine,
  Church,
  Repeat,
  Calendar,
  Star,
  Smile,
  Plus,
  Tag,
  type LucideIcon,
} from "lucide-react";

type IconDef = { name: string; Icon: LucideIcon; keywords: string };

// Biblioteca curada para finanças da casa (nomes = valor salvo no banco).
export const ICON_LIBRARY: IconDef[] = [
  // Moradia / casa
  { name: "home", Icon: Home, keywords: "casa moradia lar" },
  { name: "building", Icon: Building2, keywords: "predio apartamento aluguel condominio" },
  { name: "bed", Icon: BedDouble, keywords: "cama quarto dormir" },
  { name: "sofa", Icon: Sofa, keywords: "sofa moveis sala" },
  { name: "lightbulb", Icon: Lightbulb, keywords: "luz energia lampada" },
  { name: "plug", Icon: Plug, keywords: "energia eletrica tomada" },
  { name: "droplet", Icon: Droplet, keywords: "agua conta" },
  { name: "flame", Icon: Flame, keywords: "gas fogo aquecimento" },
  { name: "wifi", Icon: Wifi, keywords: "internet wifi rede" },
  { name: "trash", Icon: Trash2, keywords: "lixo limpeza" },
  { name: "wrench", Icon: Wrench, keywords: "manutencao conserto reparo" },
  { name: "hammer", Icon: Hammer, keywords: "reforma obra construcao" },

  // Mercado / alimentação
  { name: "shopping-cart", Icon: ShoppingCart, keywords: "mercado compras supermercado" },
  { name: "shopping-bag", Icon: ShoppingBag, keywords: "compras sacola loja" },
  { name: "store", Icon: Store, keywords: "loja mercearia comercio" },
  { name: "package", Icon: Package, keywords: "encomenda entrega pacote" },
  { name: "utensils", Icon: Utensils, keywords: "restaurante comida almoco jantar" },
  { name: "coffee", Icon: Coffee, keywords: "cafe lanche padaria" },
  { name: "beer", Icon: Beer, keywords: "cerveja bar bebida" },
  { name: "wine", Icon: Wine, keywords: "vinho bebida" },
  { name: "pizza", Icon: Pizza, keywords: "pizza delivery fastfood" },
  { name: "apple", Icon: Apple, keywords: "fruta feira saudavel" },
  { name: "carrot", Icon: Carrot, keywords: "verdura legume feira" },
  { name: "milk", Icon: Milk, keywords: "leite laticinio" },
  { name: "cookie", Icon: Cookie, keywords: "doce biscoito guloseima" },
  { name: "beef", Icon: Beef, keywords: "carne acougue" },
  { name: "fish", Icon: Fish, keywords: "peixe frutos do mar" },
  { name: "ice-cream", Icon: IceCream, keywords: "sorvete sobremesa" },

  // Transporte
  { name: "car", Icon: Car, keywords: "carro transporte veiculo" },
  { name: "truck", Icon: Truck, keywords: "caminhao van carga veiculo" },
  { name: "motorcycle", Icon: Bike, keywords: "moto motocicleta veiculo" },
  { name: "bus", Icon: Bus, keywords: "onibus transporte publico" },
  { name: "train", Icon: TramFront, keywords: "trem metro transporte" },
  { name: "bike", Icon: Bike, keywords: "bicicleta bike" },
  { name: "fuel", Icon: Fuel, keywords: "gasolina combustivel posto" },
  { name: "plane", Icon: Plane, keywords: "aviao viagem passagem" },
  { name: "ship", Icon: Ship, keywords: "barco navio viagem" },
  { name: "map-pin", Icon: MapPin, keywords: "local endereco mapa" },

  // Saúde / cuidados
  { name: "heart", Icon: Heart, keywords: "saude amor coracao" },
  { name: "heart-pulse", Icon: HeartPulse, keywords: "saude plano medico" },
  { name: "stethoscope", Icon: Stethoscope, keywords: "medico consulta saude" },
  { name: "pill", Icon: Pill, keywords: "remedio farmacia medicamento" },
  { name: "cross", Icon: Cross, keywords: "hospital farmacia saude" },
  { name: "activity", Icon: Activity, keywords: "saude batimento exame" },
  { name: "dumbbell", Icon: Dumbbell, keywords: "academia treino esporte" },
  { name: "bath", Icon: Bath, keywords: "banho higiene beleza" },
  { name: "scissors", Icon: Scissors, keywords: "cabelo salao barbeiro" },
  { name: "sparkles", Icon: Sparkles, keywords: "beleza estetica limpeza" },

  // Família / pets
  { name: "baby", Icon: Baby, keywords: "bebe filho crianca" },
  { name: "dog", Icon: Dog, keywords: "cachorro pet animal" },
  { name: "cat", Icon: Cat, keywords: "gato pet animal" },
  { name: "paw", Icon: PawPrint, keywords: "pet animal veterinario" },

  // Educação / trabalho
  { name: "graduation", Icon: GraduationCap, keywords: "educacao faculdade escola estudo" },
  { name: "book-open", Icon: BookOpen, keywords: "livro curso estudo" },
  { name: "book", Icon: Book, keywords: "livro leitura material" },
  { name: "pencil", Icon: Pencil, keywords: "escola material curso" },
  { name: "briefcase", Icon: Briefcase, keywords: "trabalho emprego negocio" },

  // Dinheiro / entradas
  { name: "wallet", Icon: Wallet, keywords: "carteira dinheiro" },
  { name: "piggy-bank", Icon: PiggyBank, keywords: "poupanca reserva economia" },
  { name: "banknote", Icon: Banknote, keywords: "salario dinheiro nota" },
  { name: "coins", Icon: Coins, keywords: "moedas dinheiro troco" },
  { name: "credit-card", Icon: CreditCard, keywords: "cartao credito fatura" },
  { name: "dollar", Icon: DollarSign, keywords: "dinheiro renda pagamento" },
  { name: "trending-up", Icon: TrendingUp, keywords: "investimento rendimento alta" },
  { name: "landmark", Icon: Landmark, keywords: "banco imposto governo" },
  { name: "hand-coins", Icon: HandCoins, keywords: "renda extra receber dinheiro" },
  { name: "receipt", Icon: Receipt, keywords: "conta nota boleto recibo" },
  { name: "file-text", Icon: FileText, keywords: "conta documento boleto" },

  // Lazer / diversos
  { name: "gift", Icon: Gift, keywords: "presente aniversario" },
  { name: "party", Icon: PartyPopper, keywords: "festa comemoracao evento" },
  { name: "gamepad", Icon: Gamepad2, keywords: "jogo game videogame" },
  { name: "music", Icon: Music, keywords: "musica show spotify" },
  { name: "film", Icon: Film, keywords: "cinema filme streaming" },
  { name: "tv", Icon: Tv, keywords: "tv assinatura streaming" },
  { name: "ticket", Icon: Ticket, keywords: "ingresso evento show" },
  { name: "camera", Icon: Camera, keywords: "foto camera hobby" },
  { name: "headphones", Icon: Headphones, keywords: "fone musica audio" },
  { name: "shirt", Icon: Shirt, keywords: "roupa vestuario" },
  { name: "footprints", Icon: Footprints, keywords: "calcado tenis sapato" },
  { name: "umbrella", Icon: Umbrella, keywords: "seguro protecao" },
  { name: "sun", Icon: Sun, keywords: "ferias lazer" },
  { name: "tree", Icon: TreePine, keywords: "natureza parque passeio" },
  { name: "church", Icon: Church, keywords: "igreja doacao dizimo" },

  // Tecnologia / assinaturas
  { name: "phone", Icon: Phone, keywords: "telefone celular conta" },
  { name: "smartphone", Icon: Smartphone, keywords: "celular telefone" },
  { name: "laptop", Icon: Laptop, keywords: "notebook computador" },
  { name: "monitor", Icon: Monitor, keywords: "computador monitor tela" },
  { name: "repeat", Icon: Repeat, keywords: "assinatura recorrente mensal" },
  { name: "calendar", Icon: Calendar, keywords: "mensal agenda data" },

  // Genéricos
  { name: "star", Icon: Star, keywords: "favorito destaque" },
  { name: "smile", Icon: Smile, keywords: "lazer diversao" },
  { name: "plus", Icon: Plus, keywords: "extra outros adicional" },
  { name: "tag", Icon: Tag, keywords: "outros geral etiqueta" },
];

const MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_LIBRARY.map((i) => [i.name, i.Icon]),
);

// Aliases para nomes antigos que possam existir no banco
MAP["car-front"] = Car;

export const ICON_OPTIONS = ICON_LIBRARY.map((i) => i.name);

export function CategoryIcon({
  name,
  className,
}: {
  name: string | null;
  className?: string;
}) {
  const Icon = (name && MAP[name]) || Tag;
  return <Icon className={className} />;
}
